# example netlify.toml
[dev]
  targetPort = 3000
  command = "pnpm run dev"

[build]
  command = "pnpm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
    
[[redirects]]
  from = "/api/*" # simplify all calls to serverless functions
  to = "/.netlify/functions/:splat" # all function calls will go to this path
  status = 200 # ok code
  force = true # ensure to always redirect

[[redirects]]
  from = "/member/*"
  to = "/member/:splat"
  force = true
  status = 200
  conditions = {Role = ["member"]}

[[redirects]]
  from = "/member/*"
  to = "/member-only"
  force = true
  status = 401

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  force = true
  status = 200
  conditions = {Role = ["editor", "admin"]}

[[redirects]]
  from = "/admin/*"
  to = "/"
  force = true
  status = 401
